export const Discipline = Object.freeze({
	HTML: "HTML",
	CSS: "CSS",
	JS: "JS",
	REACT: "React",
	SVG: "Vector Graphics",
	UNITY: "Unity",
	JAVA: "Java",
	CSHARP: "CSHARP",
	C: "C",
	ART2D: "2D Art",
	ART3D: "3D Art",
	AUTODESK3DSMAX: "3dsmax",
	AUTODESKMAYA: "Maya",
	ANIMATION2D: "2D Animation",
});